package io.magnetic.vamp_core.container_driver.notification

import io.vamp.common.notification.{DefaultPackageMessageResolverProvider, LoggingNotificationProvider}

trait ContainerDriverNotificationProvider extends LoggingNotificationProvider with DefaultPackageMessageResolverProvider