package io.vamp.core.pulse.notification

import io.vamp.common.notification.{ DefaultPackageMessageResolverProvider, LoggingNotificationProvider }

trait PulseNotificationProvider extends LoggingNotificationProvider with DefaultPackageMessageResolverProvider