package io.vamp.core.pulse.notification

import io.vamp.common.notification.{DefaultPackageMessageResolverProvider, LoggingNotificationProvider}

trait PulseDriverNotificationProvider extends LoggingNotificationProvider with DefaultPackageMessageResolverProvider