
console.log("VAMP_KEY_VALUE_STORE_TYPE       : " + process.env.VAMP_KEY_VALUE_STORE_TYPE);
console.log("VAMP_KEY_VALUE_STORE_CONNECTION : " + process.env.VAMP_KEY_VALUE_STORE_CONNECTION);
console.log("VAMP_KEY_VALUE_STORE_ROOT_PATH  : " + process.env.VAMP_KEY_VALUE_STORE_ROOT_PATH);
console.log("VAMP_WORKFLOW_DIRECTORY         : " + process.env.VAMP_WORKFLOW_DIRECTORY);
console.log("VAMP_ELASTICSEARCH_CONNECTION   : " + process.env.VAMP_ELASTICSEARCH_CONNECTION);
