package io.magnetic.vamp_core.pulse_driver.notification

import io.magnetic.vamp_common.notification.{DefaultPackageMessageResolverProvider, LoggingNotificationProvider}

trait PulseDriverNotificationProvider extends LoggingNotificationProvider with DefaultPackageMessageResolverProvider