package io.vamp.router_driver.notification

import io.vamp.common.notification.{ DefaultPackageMessageResolverProvider, LoggingNotificationProvider }

trait RouterDriverNotificationProvider extends LoggingNotificationProvider with DefaultPackageMessageResolverProvider