CREATE TABLE IF NOT EXISTS Artifacts (
 ID INTEGER PRIMARY KEY AUTOINCREMENT,
 Version TEXT NOT NULL,
 Command TEXT NOT NULL,
 Type TEXT NOT NULL,
 Name TEXT NOT NULL,
 Definition TEXT
);

CREATE TABLE IF NOT EXISTS Config (
 ID INTEGER PRIMARY KEY AUTOINCREMENT ,
 Namespace TEXT NOT NULL UNIQUE,
 Definition TEXT NOT NULL
)